export const freelanceSkills: string[] = [
  "SEO",
  "AR/VR",
  "Sales",
  "Negotiation",
  "Invoicing",
  "Marketing",
  "Networking",
  "Content Creation",
  "Digital Marketing",
  "Graphic Design",
  "Copywriting",
  "Adaptability",
  "Research",
  "Web Development",
  "Data Analysis",
  "Financial Planning",
  "Problem Solving",
  "Project Management",
  "Copywriting",
  "Research",
  "Web Development",
  "Data Analysis",
  "Financial Planning",
  "Problem Solving",
  "Project Management",
  "Copywriting",
  "Adaptability",
  "Research",
  "Web Development",
  "Data Analysis",
  "Financial Planning",
  "Problem Solving",
  "Project Management",
];

const generateServiceId = () => Math.floor(Math.random() * 1000000) + "26opgs";

export const freelanceServices: {
  id: string;
  businessName: string;
  service: string;
  price: number;
  servicePoster: string;
  businessLogo: string;
}[] = [
  {
    id: generateServiceId(),
    businessName: "Bitronic",
    service: "Borobazar React Next Grocery Template",
    price: 70.0,
    servicePoster: require("../../Assets/poster1.png"),
    businessLogo: require("../../Assets/dev_logo1.png"),
  },
  {
    id: generateServiceId(),
    businessName: "Omnico Team",
    service: "ChawkBazar Laravel Flutter Mobile App",
    price: 39.0,
    servicePoster: require("../../Assets/poster2.png"),
    businessLogo: require("../../Assets/dev_logo2.png"),
  },

  {
    id: generateServiceId(),
    businessName: "BentaSoft",
    service: "MagazzinePro Lyfestyle Blog Template",
    price: 30.0,
    servicePoster: require("../../Assets/poster3.png"),
    businessLogo: require("../../Assets/dev_logo3.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Omatron",
    service: "StoryHub WordPress Blog Theme",
    price: 55.0,
    servicePoster: require("../../Assets/poster4.png"),
    businessLogo: require("../../Assets/dev_logo4.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Temper studios",
    service: "Rental & Booking WP plugin for WooCommerce",
    price: 29.0,
    servicePoster: require("../../Assets/poster5.png"),
    businessLogo: require("../../Assets/dev_logo5.png"),
  },
  {
    id: generateServiceId(),
    businessName: "Bitronic",
    service: "Borobazar React Next Grocery Template",
    price: 70.0,
    servicePoster: require("../../Assets/poster1.png"),
    businessLogo: require("../../Assets/dev_logo1.png"),
  },
  {
    id: generateServiceId(),
    businessName: "Omnico Team",
    service: "ChawkBazar Laravel Flutter Mobile App",
    price: 39.0,
    servicePoster: require("../../Assets/poster2.png"),
    businessLogo: require("../../Assets/dev_logo2.png"),
  },

  {
    id: generateServiceId(),
    businessName: "BentaSoft",
    service: "MagazzinePro Lyfestyle Blog Template",
    price: 30.0,
    servicePoster: require("../../Assets/poster3.png"),
    businessLogo: require("../../Assets/dev_logo3.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Omatron",
    service: "StoryHub WordPress Blog Theme",
    price: 55.0,
    servicePoster: require("../../Assets/poster4.png"),
    businessLogo: require("../../Assets/dev_logo4.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Temper studios",
    service: "Rental & Booking WP plugin for WooCommerce",
    price: 29.0,
    servicePoster: require("../../Assets/poster5.png"),
    businessLogo: require("../../Assets/dev_logo5.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Bitronic",
    service: "Borobazar React Next Grocery Template",
    price: 70.0,
    servicePoster: require("../../Assets/poster1.png"),
    businessLogo: require("../../Assets/dev_logo1.png"),
  },
  {
    id: generateServiceId(),
    businessName: "Omnico Team",
    service: "ChawkBazar Laravel Flutter Mobile App",
    price: 39.0,
    servicePoster: require("../../Assets/poster2.png"),
    businessLogo: require("../../Assets/dev_logo2.png"),
  },

  {
    id: generateServiceId(),
    businessName: "BentaSoft",
    service: "MagazzinePro Lyfestyle Blog Template",
    price: 30.0,
    servicePoster: require("../../Assets/poster3.png"),
    businessLogo: require("../../Assets/dev_logo3.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Bitronic",
    service: "Borobazar React Next Grocery Template",
    price: 70.0,
    servicePoster: require("../../Assets/poster1.png"),
    businessLogo: require("../../Assets/dev_logo1.png"),
  },
  {
    id: generateServiceId(),
    businessName: "Omnico Team",
    service: "ChawkBazar Laravel Flutter Mobile App",
    price: 39.0,
    servicePoster: require("../../Assets/poster2.png"),
    businessLogo: require("../../Assets/dev_logo2.png"),
  },

  {
    id: generateServiceId(),
    businessName: "BentaSoft",
    service: "MagazzinePro Lyfestyle Blog Template",
    price: 30.0,
    servicePoster: require("../../Assets/poster3.png"),
    businessLogo: require("../../Assets/dev_logo3.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Omatron",
    service: "StoryHub WordPress Blog Theme",
    price: 55.0,
    servicePoster: require("../../Assets/poster4.png"),
    businessLogo: require("../../Assets/dev_logo4.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Bitronic",
    service: "Borobazar React Next Grocery Template",
    price: 70.0,
    servicePoster: require("../../Assets/poster1.png"),
    businessLogo: require("../../Assets/dev_logo1.png"),
  },
  {
    id: generateServiceId(),
    businessName: "Omnico Team",
    service: "ChawkBazar Laravel Flutter Mobile App",
    price: 39.0,
    servicePoster: require("../../Assets/poster2.png"),
    businessLogo: require("../../Assets/dev_logo2.png"),
  },

  {
    id: generateServiceId(),
    businessName: "BentaSoft",
    service: "MagazzinePro Lyfestyle Blog Template",
    price: 30.0,
    servicePoster: require("../../Assets/poster3.png"),
    businessLogo: require("../../Assets/dev_logo3.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Omatron",
    service: "StoryHub WordPress Blog Theme",
    price: 55.0,
    servicePoster: require("../../Assets/poster4.png"),
    businessLogo: require("../../Assets/dev_logo4.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Temper studios",
    service: "Rental & Booking WP plugin for WooCommerce",
    price: 29.0,
    servicePoster: require("../../Assets/poster5.png"),
    businessLogo: require("../../Assets/dev_logo5.png"),
  },
  {
    id: generateServiceId(),
    businessName: "Bitronic",
    service: "Borobazar React Next Grocery Template",
    price: 70.0,
    servicePoster: require("../../Assets/poster1.png"),
    businessLogo: require("../../Assets/dev_logo1.png"),
  },
  {
    id: generateServiceId(),
    businessName: "Omnico Team",
    service: "ChawkBazar Laravel Flutter Mobile App",
    price: 39.0,
    servicePoster: require("../../Assets/poster2.png"),
    businessLogo: require("../../Assets/dev_logo2.png"),
  },

  {
    id: generateServiceId(),
    businessName: "BentaSoft",
    service: "MagazzinePro Lyfestyle Blog Template",
    price: 30.0,
    servicePoster: require("../../Assets/poster3.png"),
    businessLogo: require("../../Assets/dev_logo3.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Omatron",
    service: "StoryHub WordPress Blog Theme",
    price: 55.0,
    servicePoster: require("../../Assets/poster4.png"),
    businessLogo: require("../../Assets/dev_logo4.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Temper studios",
    service: "Rental & Booking WP plugin for WooCommerce",
    price: 29.0,
    servicePoster: require("../../Assets/poster5.png"),
    businessLogo: require("../../Assets/dev_logo5.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Bitronic",
    service: "Borobazar React Next Grocery Template",
    price: 70.0,
    servicePoster: require("../../Assets/poster1.png"),
    businessLogo: require("../../Assets/dev_logo1.png"),
  },
  {
    id: generateServiceId(),
    businessName: "Omnico Team",
    service: "ChawkBazar Laravel Flutter Mobile App",
    price: 39.0,
    servicePoster: require("../../Assets/poster2.png"),
    businessLogo: require("../../Assets/dev_logo2.png"),
  },

  {
    id: generateServiceId(),
    businessName: "BentaSoft",
    service: "MagazzinePro Lyfestyle Blog Template",
    price: 30.0,
    servicePoster: require("../../Assets/poster3.png"),
    businessLogo: require("../../Assets/dev_logo3.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Bitronic",
    service: "Borobazar React Next Grocery Template",
    price: 70.0,
    servicePoster: require("../../Assets/poster1.png"),
    businessLogo: require("../../Assets/dev_logo1.png"),
  },
  {
    id: generateServiceId(),
    businessName: "Omnico Team",
    service: "ChawkBazar Laravel Flutter Mobile App",
    price: 39.0,
    servicePoster: require("../../Assets/poster2.png"),
    businessLogo: require("../../Assets/dev_logo2.png"),
  },

  {
    id: generateServiceId(),
    businessName: "BentaSoft",
    service: "MagazzinePro Lyfestyle Blog Template",
    price: 30.0,
    servicePoster: require("../../Assets/poster3.png"),
    businessLogo: require("../../Assets/dev_logo3.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Omatron",
    service: "StoryHub WordPress Blog Theme",
    price: 55.0,
    servicePoster: require("../../Assets/poster4.png"),
    businessLogo: require("../../Assets/dev_logo4.png"),
  },
  {
    id: generateServiceId(),
    businessName: "BentaSoft",
    service: "MagazzinePro Lyfestyle Blog Template",
    price: 30.0,
    servicePoster: require("../../Assets/poster3.png"),
    businessLogo: require("../../Assets/dev_logo3.png"),
  },

  {
    id: generateServiceId(),
    businessName: "Omatron",
    service: "StoryHub WordPress Blog Theme",
    price: 55.0,
    servicePoster: require("../../Assets/poster4.png"),
    businessLogo: require("../../Assets/dev_logo4.png"),
  },
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const experts = [
  {
    id: 1,
    name: "Maxicon Soft Tech",
    imageUrl: require("../../Assets/e-image.png"),
  },
  {
    id: 2,
    name: "Tech Innovators",
    imageUrl: require("../../Assets/e-image2.png"),
  },
  {
    id: 3,
    name: "Creative Solutions",
    imageUrl: require("../../Assets/e-image3.png"),
  },
  {
    id: 4,
    name: "NextGen Technologies",
    imageUrl: require("../../Assets/e-image4.png"),
  },
  {
    id: 5,
    name: "Future Vision",
    imageUrl: require("../../Assets/e-image.png"),
  },
  {
    id: 6,
    name: "Bright Ideas",
    imageUrl: require("../../Assets/e-image2.png"),
  },
  {
    id: 7,
    name: "Innovative Minds",
    imageUrl: require("../../Assets/e-image3.png"),
  },
  {
    id: 8,
    name: "Tech Pioneers",
    imageUrl: require("../../Assets/e-image4.png"),
  },
  {
    id: 9,
    name: "Visionary Solutions",
    imageUrl: require("../../Assets/e-image.png"),
  },
  {
    id: 10,
    name: "Creative Tech",
    imageUrl: require("../../Assets/e-image2.png"),
  },
  {
    id: 11,
    name: "Tech Gurus",
    imageUrl: require("../../Assets/e-image3.png"),
  },
  {
    id: 12,
    name: "Future Tech",
    imageUrl: require("../../Assets/e-image4.png"),
  },
  {
    id: 13,
    name: "Bright Future",
    imageUrl: require("../../Assets/e-image.png"),
  },
  {
    id: 14,
    name: "Innovative Solutions",
    imageUrl: require("../../Assets/e-image4.png"),
  },
  {
    id: 15,
    name: "Tech Visionaries",
    imageUrl: require("../../Assets/e-image2.png"),
  },
  {
    id: 16,
    name: "Creative Minds",
    imageUrl: require("../../Assets/e-image3.png"),
  },
  {
    id: 17,
    name: "NextGen Innovators",
    imageUrl: require("../../Assets/e-image2.png"),
  },
  {
    id: 18,
    name: "Visionary Tech",
    imageUrl: require("../../Assets/e-image.png"),
  },
  {
    id: 19,
    name: "Tech Solutions",
    imageUrl: require("../../Assets/e-image4.png"),
  },
  {
    id: 20,
    name: "Future Innovators",
    imageUrl: require("../../Assets/e-image3.png"),
  },
  {
    id: 21,
    name: "Bright Minds",
    imageUrl: require("../../Assets/e-image.png"),
  },
  {
    id: 22,
    name: "Innovative Tech",
    imageUrl: require("../../Assets/e-image4.png"),
  },
  {
    id: 23,
    name: "Tech Creators",
    imageUrl: require("../../Assets/e-image2.png"),
  },
  {
    id: 24,
    name: "Visionary Innovators",
    imageUrl: require("../../Assets/e-image4.png"),
  },
  {
    id: 25,
    name: "Creative Vision",
    imageUrl: require("../../Assets/e-image.png"),
  },
  {
    id: 26,
    name: "NextGen Solutions",
    imageUrl: require("../../Assets/e-image3.png"),
  },
  {
    id: 27,
    name: "Tech Future",
    imageUrl: require("../../Assets/e-image4.png"),
  },
  {
    id: 28,
    name: "Bright Innovators",
    imageUrl: require("../../Assets/e-image.png"),
  },
  {
    id: 29,
    name: "Innovative Vision",
    imageUrl: require("../../Assets/e-image3.png"),
  },
  {
    id: 30,
    name: "Tech Minds",
    imageUrl: require("../../Assets/e-image2.png"),
  },
];
